### ISSUE TITLE
Expression count operator unsupported

### ISSUE THREAD

**Issue by fpw** [peggyjs/peggy-tracks#11]
Hi,

it seems that the expression count operator (`expression |..|`) is unsupported.

I'm getting the following error on an expression that uses `|.., ","|`:

```
... node_modules\peggy-tracks\node_modules\peggy\lib\parser.js:33
  var self = Error.call(this, message);
                   ^
peg$SyntaxError: Expected "!", "$", "&", "(", "*", "+", ".", "/", "/*", "//", ";", "?", "@", character class, code block, comment, end of line, identifier, literal, or whitespace but "|" found.
```
I guess the immediate reason is that peggy-tracks uses an older version of Peggy internally, but using the latest version still wouldn't generate a diagram that expresses the new syntax.

**Comment by hildjj** [comment]
Now that I see someone is using this, I'll put it in rotation to keep more up-to-date.

**Comment by fpw** [comment]
Thanks, that would be great! I'm developing a new assembler for the ancient PDP-8 computer, the assembler syntax is from 1965 and not really made for parsing into an AST. However, with Peggy's great feature to reject tokens with the & operator and a JavaScript fragment, I made it work. 

Now I just need to create some diagrams to create a nice documentation. 
Grammar is over here if you're interested: https://github.com/fpw/yamas/blob/main/docs/grammar.peggy

**Comment by hildjj** [comment]
This is going to be a little graphically-tricky.  Here is my proposal:

- If min is zero (either explicitly or by default), start with the look of `*`
- Otherwise, start with the look of `+`
- put the separator expression on the horizontal part of the return loop
- put some form of the count information inside the loop, justified to the right, in such a way that it won't intersect with either of the expressions.

I don't think there's any way with a sane amount of work to look into a code block as the minimum to determine if it *could* return zero.

**Comment by fpw** [comment]
Sounds good to me. Maybe the case with a code block could be visualized with a generic `{...}` as it's already done for &-blocks with code.
![Uploading InnerMacroBody.svg…]()

**Comment by hildjj** [comment]
Another point.  Either the expression for the separator will need to be reversed, or some sort of S-shaped lines will be needed.

**Comment by fpw** [comment]
Here's an example how sqlite does it: 
![grafik](https://github.com/peggyjs/peggy-tracks/assets/5798899/36d71d0e-63a5-420e-8786-e4ce49c2758f)

**Comment by hildjj** [comment]
That example from sqlite doesn't have something like this in it's delimiter:

```peg.js
params = expr|1.., "," [ \t]*|
```

when the repeat comes around, it's going right-to-left instead of left-to-right.  Visually, it would read `[ \t]* ","` instead of `"," [ \t]*`

**Comment by hildjj** [comment]
I've got this mostly-working, it still needs cleanup and testing.  Another issue I've found:

```peg.js
url = "www"|1..2,"."|
```

Currently generates:

![u](https://github.com/peggyjs/peggy-tracks/assets/93963/521f9a7e-1ce9-42ee-9817-609b0e94ea36)

Visually, however, this means 2..3, not 1..2.

**Comment by hildjj** [comment]
This is the best I've come up with so far for the Sequence problem:
![u](https://github.com/peggyjs/peggy-tracks/assets/93963/e6cec278-d645-4743-83d2-7ea4b00c6ef0)

**Comment by fpw** [comment]
Wow, didn't know the operator had these capabilities - but looks very good to me.

**Comment by hildjj** [comment]
Here are two choices:

- Right: ![repeat-right](https://github.com/peggyjs/peggy-tracks/assets/93963/7b9e6274-07f0-47c1-b74d-240a461d2ba8)
- Left: ![repeat-left](https://github.com/peggyjs/peggy-tracks/assets/93963/e278a417-d442-42c6-9c1c-ba9cdba0b654)

I think I like left better, because it more accurately captures the repeat counts.  Opinions?

**Comment by hildjj** [comment]
I could put a box around the whole repeat phrase either way, if that would be clearer.

**Comment by fpw** [comment]
Hm.. I personally like the box variant the most: It does add more visual distraction by introducing another line style, but I think it's the only variant that makes the situation absolutely clear.
In the "Right" variant, it looks like the edge after label has to be taken at least once, which doesn't reflect what the operator is doing.
And in the "Left" variant, it's on a straight edge, so it's not clear from just looking at the diagram.

**Comment by hildjj** [comment]
I ended up with this:

![repeat](https://github.com/peggyjs/peggy-tracks/assets/93963/9d3823a8-349d-4f6a-9e77-304e5c07bdb4)

**Comment by fpw** [comment]
Thanks a lot!
