### ISSUE TITLE
Only expand selected rules

### ISSUE THREAD

**Issue by nichtich** [peggyjs/peggy-tracks#21]
Expanding *all* rules can result in a very complex diagram. An option to select which rules to expand (and/or how many levels of recursion) would help. How about this:

- change the option `--expand` to a numeric argument with `0` as default and `all` alias for a very large number
- change [probably this](https://github.com/peggyjs/peggy-tracks/blob/5a0e9cc4ecd77d7da7eb4aeec3b719cee7c36fad/lib/index.js#L137-L141) to decrease `expand` for each recursion.

This way callers can decide the depth of expansion and get arbitrary selections of the grammar when combined with `--start`.

**Comment by hildjj** [comment]
If expand starts to require a parameter, that would be a breaking change.  If expand takes an optional parameter, it would also be a breaking change to `peggy-tracks -e test.peggy`.  We could add a (somewhat redundant) new option called "depth" or "maxDepth" that would require an integer parameter.  0, the default, would mean no expansion. --expand would set depth to Infinity.
