### ISSUE TITLE
Crash on |n| repetitions syntax

### ISSUE THREAD

**Issue by nichtich** [peggyjs/peggy-tracks#23]
This works

    echo 'x="x"|2..2|' > x.peggy; ./bin/peggy-tracks.js x.peggy

This does not

    echo 'x="x"|2|' > x.peggy; ./bin/peggy-tracks.js x.peggy

~~~
TypeError: Cannot read properties of null (reading 'type')
    at Object.repeated (file:///.../peggy-tracks/lib/index.js:116:18)
~~~

**Comment by hildjj** [comment]
Fixed in v3.2.0
